JSON.parse変更
Akihiro0710/socket-test pull request #7
Opened 2018-06-12 07:01 UTC by yuki3709

2018-06-16 09:57 UTC, tail12 requested changes
ロジック部分はいいので，インデント幅を2に統一したほうがJSっぽいかも！
竹内に頼まれたので，レビューしました！わからないことがあったら竹内に聞いて！！！

2018-06-16 09:57 UTC, tail12 commented on public/js_screen/index.js
>      circle.forEach(function (circle) {
`circle`がforEach内のローカル変数の`circle`と同じ名前になっているので変更したほうがいいかも．
`circle.forEach`のcircleは複数形にするほうが良いよ(配列なので)．

2018-06-16 09:57 UTC, tail12 commented on public/js_screen/index.js
> +                }
curlyになっているので，ここは
```
if () {
  ...
} else {
  ...
}
```
のほうがいいかも．(任せます)

2018-06-16 09:57 UTC, tail12 commented on public/js_screen/index.js
この空行いらないかなー

2018-06-16 09:57 UTC, tail12 commented on public/js_screen/index.js
> +            var futurelocX = circle.locX + circle.speedX;
`futurelocX -> futureLocX`かなー！

2018-06-16 09:58 UTC, Akihiro0710 commented
contextが宣言されてない

2018-06-16 10:00 UTC, tail12 approved these changes

2018-06-19 08:18 UTC, yuki3709 commented
プロトタイプを使ってCircleメソッドを定義
runメソッドにdrawとdiscriminateCommandを書いてdrawには描画処理のみ記述

2018-06-19 08:21 UTC, yuki3709 commented
指摘された部分も修正しました

2018-06-19 10:57 UTC, yuki3709 commented
円の向きを極座標で保持させた

2018-06-20 12:54 UTC, merged